// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfuywdvvjsmbqtawpope.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmdXl3ZHZ2anNtYnF0YXdwb3BlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyOTMxNzUsImV4cCI6MjA3MTg2OTE3NX0.9UM0vVWL_CnbAZGO8b3i7k4t74dvuSkihdeSh7TeCJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});